# ref: https://github.com/conventional-changelog/commitlint/blob/4360d5/.circleci/config.yml
version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  build:
    steps:
      - run:
          name: Build packages
          command: npm run build
  tsc:
    steps:
      - run:
          name: Type check
          command: npx tsc
  run-node:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - install
      - build
      - tsc
jobs:
  v10:
    docker:
      - image: node:10.15.2
    steps:
      - run-node

workflows:
  node:
    jobs:
      - v10
