name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Type Check
        run: yarn tsc --noEmit && yarn service-worker --noEmit
      - name: Check ESLint Rules
        run: yarn eslint src
      - name: Check dependency license list sync
        run: yarn jest
